### PR TITLE
Replace usage of sync-exec with child_process.execSync

### LINKED ISSUE #2: Vulnerabilities in sync-exec
`npm audit` shows vulnerabilities in the sync-exec dependency: https://nodesecurity.io/advisories/310

### PR DESCRIPTION
**Pull request by unional**
The difference between `sync-exec` and `child_process.execSync` is that `execSync` throws an error and return a Buffer. `sync-exec` returns an object with status.

Thus the code needs to be changed a bit in order to work correctly.

Please use Squash command to merge. 🌷 

This closes #2 and supersedes #3 as @felipewer may not be active.

EDIT: correction, actually I noticed @felipewer was active to fix the Travis issue.
Feel free to accept his PR when my changes are merged.

### CODE REVIEW

**Comment by shime** [comment]
Wow, thanks so much for this! Unfortunately, I don't have the access rights to your repo, so I can't squash those commits.

Can you squash all of your commits in the first one (`git rebase -i 71c6c4a`) and then replace the commit message to: "Start using child_process.execSync instead of child_process.spawnSync".

I would also like to stick with `findCommand` instead of `compose`, so if you could change that back, that would be great. Compose is too generic for a function name in my opinion and `findCommand` better describes what is done.

Also, if you could revert @felipewer's change to the package version in another commit, that would be great. I like to bump up the version in the separate commit, like how I did it in https:2ba3581ba35224bc00341793de913c3afb0abe1c.

Thank you!

**Comment by unional** [comment]
Um.... not good at git history rewrite.

By squash I mean when you merge the PR, you can choose the dropdown in Github which allows you to squash the commits in the PRs to a single commit in your master.

**Comment by shime** [comment]
I don't want to squash all of these commits into a single commit, because that will create a commit with me as an author. I want to preserve commits made and the authors that contributed.

Do this after hitting `git rebase -i 71c6c4a`:

image

It will then prompt you for the commit message of the first commit. Write the commit message I've suggested.

image

It will prompt you again for the commit message of all the commits that you have squashed, including the first commit. Leave only the commit message of the first commit.

image

Use git log to check everything is squashed correctly. If not start again with `git reflog`. Let me know if you need help with this.

If everything is okay, push it gently with `git push -f`.

**Comment by unional** [comment]
Thanks for your detail steps. It works perfectly. 🌷

**Comment by shime** [comment]
Awesome! Merging, thank you!

**Pull request merged**
