### PR TITLE
fix: ignore "could not find" message in Windows

### LINKED ISSUE #5: INFO: Could not find files for the given pattern(s). on Windows
In Windows, if `where xxx` cannot find the file,
it will emit `INFO: Could not find files for the given pattern(s).` to the console.

### PR DESCRIPTION
**Pull request by unional**
In Windows, if `where xxx` cannot find the file,
it will emit `INFO: Could not find files for the given pattern(s).` to the console.

Add `stdio: 'ignore'` to prevent that message from printing out

Fixes #5

### CODE REVIEW

**Comment by unional** [comment]
Hi @shime, is there something I can help to get this merged? Thx. 🌷

**Comment by shime** [comment]
Hi @unional, so sorry for not responding. I've been busy lately.

Can you please rebase this with master and ensure the tests are passing? I've just added a Github Action that tests on Windows too.

**Comment by unional** [comment]
done. :) thx

**Comment by shime** [comment]
Thank YOU!

**Pull request merged**
